M48
; DRILL file {KiCad (6.0.6)} date Sat Sep 17 17:37:17 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-09-17T17:37:17+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.500
%
G90
G05
T1
X148.098Y-124.568
X153.878Y-124.568
T2
X136.95Y-76.11
X163.77Y-127.0
T0
M30
